# Generated by Django 5.1 on 2024-08-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=140)),
                ('legenda', models.CharField(max_length=180)),
                ('foto', models.CharField(max_length=140)),
                ('tag', models.CharField(max_length=80)),
            ],
        ),
    ]
