# Generated by Django 5.1 on 2024-08-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_diretor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
