# Generated by Django 5.1 on 2024-08-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_aluno_cursos_adquiridos'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cursos_adquiridos',
            field=models.ManyToManyField(blank=True, null=True, related_name='alunos', to='escola.cursos'),
        ),
    ]
