# Generated by Django 5.1 on 2024-08-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0009_aluno_ativo_alter_aluno_cursos_adquiridos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cursos_adquiridos',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='escola.cursos'),
        ),
    ]
