# Generated by Django 5.1 on 2024-08-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0010_alter_aluno_cursos_adquiridos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='modulos',
            field=models.ManyToManyField(related_name='cursos', to='escola.modulos'),
        ),
    ]
