# Generated by Django 5.1 on 2024-09-01 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0013_remove_cursos_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='modulos',
        ),
        migrations.AddField(
            model_name='cursos',
            name='modulos',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.modulos'),
            preserve_default=False,
        ),
    ]
