# Generated by Django 5.1 on 2024-09-01 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0014_remove_cursos_modulos_cursos_modulos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='modulos',
        ),
        migrations.AddField(
            model_name='cursos',
            name='modulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='escola.modulos'),
            preserve_default=False,
        ),
    ]
