# Generated by Django 5.1 on 2024-09-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0016_alter_cursos_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='modulo',
            field=models.CharField(choices=[('IBF', 'Ibf'), ('CDA', 'Cda')], default='', max_length=140),
        ),
    ]
