# Generated by Django 5.1 on 2024-09-01 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0017_alter_cursos_modulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modulos',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(related_name='turmas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_do_aluno', to='escola.turma'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='modulo',
            field=models.CharField(choices=[('TEOLOGIA', 'Teologia'), ('PSICOLOGIA', 'Psicologia'), ('HEBRAICO', 'hebraico')], default='', max_length=140),
        ),
    ]
