# Generated by Django 5.1 on 2024-09-09 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0018_modulos_publicado_turma_alunos_alter_aluno_turma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='boletim',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='escola.cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Faltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='escola.aluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='escola.materia')),
            ],
        ),
    ]
