# Generated by Django 5.1 on 2024-09-09 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0019_aluno_boletim_materia_faltas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='escola.turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursos',
            name='modulo',
            field=models.CharField(choices=[('TEOLOGIA', 'Teologia'), ('PSICOLOGIA', 'Psicologia'), ('HEBRAICO', 'Hebraico')], default='', max_length=140),
        ),
    ]
